DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS users;


CREATE TABLE users (
	id INTEGER NOT NULL PRIMARY KEY,
	username VARCHAR(100) NOT NULL,
	access VARCHAR(100) NOT NULL,
	fname VARCHAR(32) NOT NULL,
	lname VARCHAR(32) NOT NULL,
	description VARCHAR(200),
	token VARCHAR(100),
	dob TIMESTAMP NOT NULL,
	avatar VARCHAR(100),
	darkMode INTEGER
);

CREATE TABLE articles (
    id INTEGER NOT NULL PRIMARY KEY,
    authorId INTEGER,
	authorName VARCHAR(100),
    title VARCHAR(100)  NOT NULL,
    description VARCHAR(300),
    content VARCHAR(4000),
	publicationDate TIMESTAMP,
    imageName VARCHAR(64) NOT NULL,
	category VARCHAR(64) NOT NULL,
	FOREIGN KEY (authorId) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id INTEGER NOT NULL PRIMARY KEY,
    message VARCHAR(500) NOT NULL,
    datePosted TIMESTAMP NOT NULL,
    userId INTEGER NOT NULL,
    articleId INTEGER NOT NULL,
    FOREIGN KEY (userId) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY (articleId) REFERENCES articles(id) ON DELETE CASCADE
);

INSERT INTO users (id, username, access, fname, lname, description, token, dob, avatar,darkMode) VALUES
    (9, "Fiona", "$2b$10$j.8U5W9EahOKA3lfpEsKIuaeUYkUgpGoerowxPgf0y8YE1lo/dSOS", "Fiona", "He", "I love travelling the globe to attend the trendiest events","65589ef2-6a00-4b28-9227-8714b329aec2", "2000-05-05","avatar3.png",0),
    (10, "Yaping", "$2b$10$Ezi8HCHCbmHgrcXxX3kR7u0gvFXf.Zyf7gbD3u1taBG6JKwkHtayq", "Yaping", "Wei", "I love travelling the word to discover new wines!","ec85535e-5e70-4b9e-b1e1-b56ffcd2767b", "1999-07-050","avatar5.png",0),
    (11, "Ziek", "$2b$10$Ezi8HCHCbmHgrcXxX3kR7uzILSH2ArO2m7JxZ1SDecLWKicT/0OBS", "Ziek" , "Hudson", "I travel the world in search of new flavours", "7f8f7e27-42af-4200-b6a2-c1ff555a15b4", "1992-07-02","avatar4.png",0),
    (7, "Kinzi", "$2b$10$vXAJo5uKRSChq3jr8PsN3OAFu9.1yxJ/r1szmW5poH.d/tCCypS7e", "Kinzi", "Ceolin", "I travel the world to experience new cultures","916e92a7-351c-4229-8b44-7d1ad20f3377", "1988-05-19","avatar1.png",0)
    ;
INSERT INTO articles (authorId, category, authorName, title, description, content, publicationDate, imageName) VALUES
    (9, 'Event', 'Fiona', 'Metallica in Tokyo', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultrices neque augue, nec pretium leo sagittis sed. Maecenas ultrices, ligula egestas lobortis blandit, sem enim commodo nibh, at tempus leo nunc vitae nisi. Vivamus venenatis porttitor nibh non elementum. Curabitur venenatis, urna ut scelerisque lobortis, turpis leo accumsan tortor, eget dictum nisi erat vel velit. Cras pulvinar fringilla diam, a posuere velit porta vitae. Donec ornare urna eget molestie pharetra. Maecenas porta vitae enim eu lobortis. Phasellus placerat metus augue, eget mattis leo malesuada id. Duis et cursus purus. Nam hendrerit, eros eu lobortis laoreet, mi sem vehicula libero, vitae ultrices nunc risus vel diam. Duis vitae feugiat mi. Phasellus fermentum libero id mi tincidunt posuere. Maecenas molestie eu leo a vestibulum. Quisque non mollis nisi. Duis tortor dui, accumsan at eleifend eget, consequat ac sapien. Nam accumsan enim tempus neque condimentum, sit amet venenatis ex fermentum.</p>
<p>Nulla suscipit, velit in fermentum pulvinar, purus turpis molestie nibh, in laoreet nisi purus ac nulla. Vivamus pellentesque pellentesque nisi, at sagittis risus sagittis et. Nam sed lacus congue, iaculis ligula vitae, laoreet ex. Nulla vel convallis lectus, nec lobortis lorem. In eget finibus lorem. Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat. Proin nec risus eros. Quisque laoreet molestie risus, at porttitor ligula dapibus eu. Aliquam erat volutpat. Vivamus nec commodo dui. Mauris diam risus, maximus id dolor et, dictum fringilla velit. Fusce tempus nunc suscipit arcu accumsan, eu luctus augue vestibulum.</p>
<p>Quisque sodales augue suscipit erat fringilla tempus. Etiam eget augue gravida, porta nisi et, pretium lectus. Praesent faucibus non nunc eget vehicula. Aliquam at sem posuere, posuere ipsum non, sagittis nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed et viverra velit. Nam id tellus est. Curabitur suscipit faucibus dignissim. In in lorem mi.</p>
<p>Sed dictum venenatis enim, in malesuada nulla auctor eu. Cras dapibus fermentum magna vitae aliquet. Nunc ut interdum tellus, a gravida nisl. Aliquam vitae mi tortor. Nam feugiat molestie diam non tempor. Morbi gravida turpis nisl. Quisque eget convallis nisi, a fringilla lorem.</p>
<p>Donec imperdiet vitae nibh vel sollicitudin. Mauris maximus vitae lectus vel fermentum. Morbi non porttitor odio, at dignissim erat. Morbi sodales arcu felis, sed ultrices quam posuere quis. Nullam vitae sagittis nulla. Nulla facilisis at velit in euismod. Aenean malesuada metus vitae volutpat accumsan. Ut imperdiet sit amet leo nec faucibus. Praesent hendrerit ut est id pellentesque. Praesent id enim sit amet leo interdum bibendum vel ut erat. Nam vel luctus urna, quis blandit arcu. Sed leo dolor, scelerisque ac massa id, efficitur aliquam diam. Nulla arcu ante, condimentum a eleifend ac, lacinia id neque. Donec quis fermentum purus. Praesent tristique enim a scelerisque tincidunt.</p>
', '2022-10-12', 'concert.jpg'),
    (9, 'Event', 'Fiona', 'Colour Run in India', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-11-01', 'colour-run.jpg'),
    (9, 'Event', 'Fiona', 'Chess Tournament in Madrid', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-08-20', 'chess.jpg'),
    (9, 'Event', 'Fiona', 'Petanque in Marseille', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-05-30', 'petanque.jpg'),
	(10, 'Food', 'Yaping', 'Vineyar in Tuscany', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultrices neque augue, nec pretium leo sagittis sed. Maecenas ultrices, ligula egestas lobortis blandit, sem enim commodo nibh, at tempus leo nunc vitae nisi. Vivamus venenatis porttitor nibh non elementum. Curabitur venenatis, urna ut scelerisque lobortis, turpis leo accumsan tortor, eget dictum nisi erat vel velit. Cras pulvinar fringilla diam, a posuere velit porta vitae. Donec ornare urna eget molestie pharetra. Maecenas porta vitae enim eu lobortis. Phasellus placerat metus augue, eget mattis leo malesuada id. Duis et cursus purus. Nam hendrerit, eros eu lobortis laoreet, mi sem vehicula libero, vitae ultrices nunc risus vel diam. Duis vitae feugiat mi. Phasellus fermentum libero id mi tincidunt posuere. Maecenas molestie eu leo a vestibulum. Quisque non mollis nisi. Duis tortor dui, accumsan at eleifend eget, consequat ac sapien. Nam accumsan enim tempus neque condimentum, sit amet venenatis ex fermentum.</p>
<p>Nulla suscipit, velit in fermentum pulvinar, purus turpis molestie nibh, in laoreet nisi purus ac nulla. Vivamus pellentesque pellentesque nisi, at sagittis risus sagittis et. Nam sed lacus congue, iaculis ligula vitae, laoreet ex. Nulla vel convallis lectus, nec lobortis lorem. In eget finibus lorem. Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat. Proin nec risus eros. Quisque laoreet molestie risus, at porttitor ligula dapibus eu. Aliquam erat volutpat. Vivamus nec commodo dui. Mauris diam risus, maximus id dolor et, dictum fringilla velit. Fusce tempus nunc suscipit arcu accumsan, eu luctus augue vestibulum.</p>
<p>Quisque sodales augue suscipit erat fringilla tempus. Etiam eget augue gravida, porta nisi et, pretium lectus. Praesent faucibus non nunc eget vehicula. Aliquam at sem posuere, posuere ipsum non, sagittis nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed et viverra velit. Nam id tellus est. Curabitur suscipit faucibus dignissim. In in lorem mi.</p>
<p>Sed dictum venenatis enim, in malesuada nulla auctor eu. Cras dapibus fermentum magna vitae aliquet. Nunc ut interdum tellus, a gravida nisl. Aliquam vitae mi tortor. Nam feugiat molestie diam non tempor. Morbi gravida turpis nisl. Quisque eget convallis nisi, a fringilla lorem.</p>
<p>Donec imperdiet vitae nibh vel sollicitudin. Mauris maximus vitae lectus vel fermentum. Morbi non porttitor odio, at dignissim erat. Morbi sodales arcu felis, sed ultrices quam posuere quis. Nullam vitae sagittis nulla. Nulla facilisis at velit in euismod. Aenean malesuada metus vitae volutpat accumsan. Ut imperdiet sit amet leo nec faucibus. Praesent hendrerit ut est id pellentesque. Praesent id enim sit amet leo interdum bibendum vel ut erat. Nam vel luctus urna, quis blandit arcu. Sed leo dolor, scelerisque ac massa id, efficitur aliquam diam. Nulla arcu ante, condimentum a eleifend ac, lacinia id neque. Donec quis fermentum purus. Praesent tristique enim a scelerisque tincidunt.</p>
', '2022-10-12', 'VinesItaly.jpg'),
    (10, 'Food', 'Yaping', 'Wine Tasting in Barcelona', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-11-01', 'wine-spain.jpg'),
    (10, 'Event', 'Yaping', 'Grape Festival', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-08-20', 'wine-fr.jpg'),
    (10, 'Food', 'Yaping', 'Vineyard Tour in California', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-05-30', 'wine-ca.jpg'),
	(11, 'Food', 'Ziek', 'Paella in Valencia', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultrices neque augue, nec pretium leo sagittis sed. Maecenas ultrices, ligula egestas lobortis blandit, sem enim commodo nibh, at tempus leo nunc vitae nisi. Vivamus venenatis porttitor nibh non elementum. Curabitur venenatis, urna ut scelerisque lobortis, turpis leo accumsan tortor, eget dictum nisi erat vel velit. Cras pulvinar fringilla diam, a posuere velit porta vitae. Donec ornare urna eget molestie pharetra. Maecenas porta vitae enim eu lobortis. Phasellus placerat metus augue, eget mattis leo malesuada id. Duis et cursus purus. Nam hendrerit, eros eu lobortis laoreet, mi sem vehicula libero, vitae ultrices nunc risus vel diam. Duis vitae feugiat mi. Phasellus fermentum libero id mi tincidunt posuere. Maecenas molestie eu leo a vestibulum. Quisque non mollis nisi. Duis tortor dui, accumsan at eleifend eget, consequat ac sapien. Nam accumsan enim tempus neque condimentum, sit amet venenatis ex fermentum.</p>
<p>Nulla suscipit, velit in fermentum pulvinar, purus turpis molestie nibh, in laoreet nisi purus ac nulla. Vivamus pellentesque pellentesque nisi, at sagittis risus sagittis et. Nam sed lacus congue, iaculis ligula vitae, laoreet ex. Nulla vel convallis lectus, nec lobortis lorem. In eget finibus lorem. Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat. Proin nec risus eros. Quisque laoreet molestie risus, at porttitor ligula dapibus eu. Aliquam erat volutpat. Vivamus nec commodo dui. Mauris diam risus, maximus id dolor et, dictum fringilla velit. Fusce tempus nunc suscipit arcu accumsan, eu luctus augue vestibulum.</p>
<p>Quisque sodales augue suscipit erat fringilla tempus. Etiam eget augue gravida, porta nisi et, pretium lectus. Praesent faucibus non nunc eget vehicula. Aliquam at sem posuere, posuere ipsum non, sagittis nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed et viverra velit. Nam id tellus est. Curabitur suscipit faucibus dignissim. In in lorem mi.</p>
<p>Sed dictum venenatis enim, in malesuada nulla auctor eu. Cras dapibus fermentum magna vitae aliquet. Nunc ut interdum tellus, a gravida nisl. Aliquam vitae mi tortor. Nam feugiat molestie diam non tempor. Morbi gravida turpis nisl. Quisque eget convallis nisi, a fringilla lorem.</p>
<p>Donec imperdiet vitae nibh vel sollicitudin. Mauris maximus vitae lectus vel fermentum. Morbi non porttitor odio, at dignissim erat. Morbi sodales arcu felis, sed ultrices quam posuere quis. Nullam vitae sagittis nulla. Nulla facilisis at velit in euismod. Aenean malesuada metus vitae volutpat accumsan. Ut imperdiet sit amet leo nec faucibus. Praesent hendrerit ut est id pellentesque. Praesent id enim sit amet leo interdum bibendum vel ut erat. Nam vel luctus urna, quis blandit arcu. Sed leo dolor, scelerisque ac massa id, efficitur aliquam diam. Nulla arcu ante, condimentum a eleifend ac, lacinia id neque. Donec quis fermentum purus. Praesent tristique enim a scelerisque tincidunt.</p>
', '2022-10-12', 'paella.jpg'),
    (11, 'Food', 'Ziek', 'Farm Tour in Marlborough', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-11-01', 'cabbage.jpg'),
    (11, 'Event', 'Ziek', 'Seafood Festival in Oslo', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-08-20', 'dinner.jpg'),
    (11, 'Food', 'Ziek', 'Ramen in koichi', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-05-30', 'ramen.jpg'),
	(7, 'Travel', 'Kinzi', 'Korea', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam ultrices neque augue, nec pretium leo sagittis sed. Maecenas ultrices, ligula egestas lobortis blandit, sem enim commodo nibh, at tempus leo nunc vitae nisi. Vivamus venenatis porttitor nibh non elementum. Curabitur venenatis, urna ut scelerisque lobortis, turpis leo accumsan tortor, eget dictum nisi erat vel velit. Cras pulvinar fringilla diam, a posuere velit porta vitae. Donec ornare urna eget molestie pharetra. Maecenas porta vitae enim eu lobortis. Phasellus placerat metus augue, eget mattis leo malesuada id. Duis et cursus purus. Nam hendrerit, eros eu lobortis laoreet, mi sem vehicula libero, vitae ultrices nunc risus vel diam. Duis vitae feugiat mi. Phasellus fermentum libero id mi tincidunt posuere. Maecenas molestie eu leo a vestibulum. Quisque non mollis nisi. Duis tortor dui, accumsan at eleifend eget, consequat ac sapien. Nam accumsan enim tempus neque condimentum, sit amet venenatis ex fermentum.</p>
<p>Nulla suscipit, velit in fermentum pulvinar, purus turpis molestie nibh, in laoreet nisi purus ac nulla. Vivamus pellentesque pellentesque nisi, at sagittis risus sagittis et. Nam sed lacus congue, iaculis ligula vitae, laoreet ex. Nulla vel convallis lectus, nec lobortis lorem. In eget finibus lorem. Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat. Proin nec risus eros. Quisque laoreet molestie risus, at porttitor ligula dapibus eu. Aliquam erat volutpat. Vivamus nec commodo dui. Mauris diam risus, maximus id dolor et, dictum fringilla velit. Fusce tempus nunc suscipit arcu accumsan, eu luctus augue vestibulum.</p>
<p>Quisque sodales augue suscipit erat fringilla tempus. Etiam eget augue gravida, porta nisi et, pretium lectus. Praesent faucibus non nunc eget vehicula. Aliquam at sem posuere, posuere ipsum non, sagittis nibh. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed et viverra velit. Nam id tellus est. Curabitur suscipit faucibus dignissim. In in lorem mi.</p>
<p>Sed dictum venenatis enim, in malesuada nulla auctor eu. Cras dapibus fermentum magna vitae aliquet. Nunc ut interdum tellus, a gravida nisl. Aliquam vitae mi tortor. Nam feugiat molestie diam non tempor. Morbi gravida turpis nisl. Quisque eget convallis nisi, a fringilla lorem.</p>
<p>Donec imperdiet vitae nibh vel sollicitudin. Mauris maximus vitae lectus vel fermentum. Morbi non porttitor odio, at dignissim erat. Morbi sodales arcu felis, sed ultrices quam posuere quis. Nullam vitae sagittis nulla. Nulla facilisis at velit in euismod. Aenean malesuada metus vitae volutpat accumsan. Ut imperdiet sit amet leo nec faucibus. Praesent hendrerit ut est id pellentesque. Praesent id enim sit amet leo interdum bibendum vel ut erat. Nam vel luctus urna, quis blandit arcu. Sed leo dolor, scelerisque ac massa id, efficitur aliquam diam. Nulla arcu ante, condimentum a eleifend ac, lacinia id neque. Donec quis fermentum purus. Praesent tristique enim a scelerisque tincidunt.</p>
', '2022-10-12', 'Korea.jpg'),
    (7, 'Travel', 'Kinzi', 'Japan', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-11-01', 'Japan.jpg'),
    (7, 'Travel', 'Kinzi', 'Italy', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-08-20', 'Italy.jpg'),
    (7, 'Travel', 'Kinzi', 'France', 'Sed consequat neque a augue lobortis, id aliquet erat sodales. Phasellus in justo risus. Duis eget velit lectus. Nullam venenatis dolor ut dignissim placerat.', '<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent condimentum massa augue, vitae consectetur nunc tristique ut. Integer pellentesque efficitur porttitor. Donec sit amet elit eget justo aliquam interdum sit amet sit amet felis. Phasellus non metus vitae diam porttitor interdum. Nulla eu ipsum congue, blandit sapien sit amet, vestibulum eros. Nunc vulputate lorem a tortor sollicitudin volutpat. Donec eu odio et erat convallis laoreet nec vitae erat. Suspendisse aliquam, dolor quis sodales euismod, tortor sem cursus lectus, in tristique metus leo eu lacus. Maecenas quis enim eget ex efficitur dignissim sed non massa. Cras a diam commodo, gravida enim quis, porttitor ipsum. Vestibulum cursus mauris ullamcorper, mattis neque sed, condimentum mauris. Vestibulum arcu erat, varius nec molestie a, eleifend ut dui. Ut non nulla magna. Integer euismod velit vel tortor tincidunt, quis varius massa sagittis. Nam maximus lacus sit amet urna pharetra, sed interdum nibh egestas. Donec risus lorem, tincidunt quis luctus ut, ullamcorper ac sem.</p>
<p>Sed a vehicula sem. Curabitur a mi eget leo egestas consequat dapibus vitae ligula. Suspendisse gravida sem eget rutrum condimentum. Sed nisi arcu, vestibulum nec massa non, mollis pretium sapien. Sed eu odio vulputate, faucibus mauris a, feugiat massa. Fusce velit ante, commodo vitae condimentum at, semper id diam. Sed fringilla tempor arcu, eu convallis purus molestie eleifend. Nam tincidunt eu velit tincidunt molestie. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Suspendisse at elit feugiat, rhoncus metus at, tempus lectus.</p>
<p>Sed lacinia magna ipsum, nec mattis est pretium id. Quisque libero turpis, dapibus et ligula in, feugiat accumsan est. Etiam justo nisi, tempus non mi nec, vestibulum condimentum quam. Aenean in neque elit. Quisque ac risus vel sem ornare viverra interdum a purus. Quisque eget enim tortor. Nulla lobortis suscipit consequat. Vivamus posuere, mauris mollis hendrerit faucibus, arcu elit dictum enim, sed sollicitudin enim mauris sed sem. Nulla facilisi. Fusce eleifend ultricies sem a posuere. Phasellus consectetur ac augue id viverra. Mauris ultricies ipsum ipsum, non ullamcorper metus tincidunt non. Phasellus efficitur, erat sit amet porttitor vestibulum, massa lacus convallis nisi, eu maximus nunc dui at lorem. Vestibulum suscipit vestibulum justo, sit amet auctor metus. Nullam elementum semper dui quis imperdiet. Donec eget massa viverra odio finibus varius.</p>
<p>Maecenas a aliquet odio, sit amet aliquet urna. Duis dignissim accumsan mauris, at volutpat magna vehicula vel. Donec feugiat lobortis diam, nec hendrerit neque imperdiet a. Morbi in mi sit amet lectus porta venenatis. Nulla maximus, elit consectetur malesuada luctus, purus ex auctor magna, vestibulum imperdiet magna dolor a est. Vestibulum ultricies elementum elementum. Nam molestie placerat tristique.</p>
<p>Morbi placerat nibh vitae erat sollicitudin, sed pharetra purus dictum. Aenean pretium sagittis vehicula. Nulla vitae dictum eros. Fusce rutrum, elit sed volutpat sodales, turpis diam rhoncus lectus, sed euismod mi arcu in tellus. Donec volutpat lacus ut tellus auctor, sed pellentesque lorem mattis. Mauris quis purus tincidunt, vulputate metus at, auctor sapien. Integer volutpat gravida fringilla. In eget dapibus felis. Donec ac scelerisque purus, a imperdiet mi. Ut vel lacus arcu. Nunc tincidunt eu quam tincidunt molestie. Pellentesque nulla libero, scelerisque et elit non, finibus accumsan ante. Nunc condimentum dui nunc, et tincidunt orci blandit ut.</p>
', '2022-05-30', 'Paris.jpg');

INSERT INTO comments (message, datePosted, userId, articleId) VALUES
("What a great article!", 6, 9,3),
("Loving the picture", 6, 10, 3),
("Think I've been here",10, 9,2),
("Is that you?", 21, 11,4),
("Damn, that looks delicious", 13, 7,11),
("I'd eat that", 11, 11, 11),
("I'm going to write screds and screds in the comment section to see if it can hold all my data, might even add some symbols @$%^@(&^*&%^(*&%*&^%$@#%^&%&*(**&%^#%$%*(&*^", 6,11,6);